debug: true
clock:
  show: true
  time_format: "%H:%M"
  show_seconds: true
  offset_x: 3
  offset_y: 0
  offset_delta: 1
weather:
  show_icon: true
  show_temp: false
  effects: false
  latitude: "51.178810"
  longitude: "-1.826169"
  exclude: "minutely,hourly,daily,alerts"
  units: "metric"
  language: "en"
  api_key: "YOUR_OPENWEATHERMAP_API_KEY"
  request_interval: 120
  offset_x: 22
  offset_y: 0
  offset_delta: 4
  swap_icon_temp: false
display:
  height: 8
  width: 32
  target_fps: 24
  content_refresh_rate: 1  # seconds
  effects: true
  pin: 18
  target_frequency: 800000
  dma: 10
  strip_type: 0x00081000
  inverted: false
  channel: 0
  brightness_day: 255
  brightness_night: 127
  change_brightness: true
resources:
  path: "res"
network:
  api_port: 8080