debug: true
clock:
  show: true
  time_format: "%H:%M"  # do not use any other separator than ":"
  show_seconds: true
  offset_x: 3
  offset_y: 0
  offset_delta: 1
weather:
  show_icon: true
  show_temp: false
  effects: false
  latitude: "51.178810"
  longitude: "-1.826169"
  exclude: "minutely,hourly,daily,alerts"
  units: "metric"
  language: "en"
  api_key: "YOUR_OPENWEATHERMAP_API_KEY"
  request_interval: 120
  offset_x: 22
  offset_y: 0
  offset_delta: 4
  offset_between: 2
  swap_icon_temp: false
display:
  height: 8
  width: 32
  target_fps: 24
  content_refresh_rate: 1  # seconds
  effects: true
  pin: 18
  target_frequency: 800000
  dma: 10
  strip_type: 0x00081000
  inverted: false
  channel: 0
  brightness_day: 255
  brightness_night: 127
  change_brightness: true
resources:
  path: "res"
network:
  api_port: 8080
  show_indicator: true
  indicator_connect_color: "0x00FF00"  # green
  indicator_disconnect_color: "0xFF0000"  # red
  indicator_x: 0
  indicator_y: 0
  check_interval: 5  # seconds
logging:
  level: "info"
  path: "logs"
  to_file: false
  to_console: true
  format: "%(asctime)s\t%(name)s\t%(levelname)-8s\t%(message)s\t[%(filename)s:%(lineno)d]"
  file_timestamp: "%Y-%m-%d_%H-%M-%S-%f_%a_UTC"
  max_size: 10485760  # bytes; 10 MB
  max_backups: 5
debug:
  show_segments: true
  show_grid: true